{{- if and (eq (include "s2-lite.walStorage.mode" .) "volume") (not .Values.walStorage.persistentVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "s2-lite.walStorage.claimName" . }}
  labels:
    {{- include "s2-lite.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  {{- with .Values.walStorage.persistentVolume.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.walStorage.persistentVolume.size | quote }}
{{- end }}
